require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Naming/MethodParameterName:
  Enabled: true
  AllowedNames: [at, by, db, id, in, io, ip, of, on, os, pp, to, as, v, ex, pk, u]

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/yarp-datum.rb

Style/ClassVars:
  Exclude:
    - lib/datum/connection.rb

Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Exclude:
    - lib/datum/dsn_query_parser.rb
    - lib/datum/adapter/*.rb

Naming/PredicateName:
  Exclude:
    - lib/datum/reflect.rb
