CREATE TEMPORARY TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    active BOOL NOT NULL,
    created_at TIMESTAMPTZ DEFAULT 'NOW()',
    updated_at TIMESTAMPTZ DEFAULT 'NOW()'
);
